### PR TITLE
Don't fail if parameters explicitly passed as nil

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by frodenas** [comment]
Better to fix this when parameters are gathered from the request [1] [2]? Otherwise it will be easy to mess up things if we decide later to use the parameters elsewhere.

```ruby
parameters = params.fetch(:parameters, {}) || {}
```
[1] https://github.com/cf-platform-eng/cf-containers-broker/blob/master/app/controllers/v2/service_instances_controller.rb#L10
[2] https://github.com/cf-platform-eng/cf-containers-broker/blob/master/app/controllers/v2/service_bindings_controller.rb#L10

**Comment by frodenas** [comment]
BTW, did you find the error invoking the service broker? Theoretically it parameters are nil then it should pick up an empty hash at https://github.com/cf-platform-eng/cf-containers-broker/blob/master/app/models/docker_manager.rb#L64

**Comment by drnic** [comment]
updated pr

**Comment by drnic** [comment]
cf-subway's golang code seems desperate to want to send `{"parameters": nil...}` rather than `{"parameters": {}, ...}` - trying to fix bug on both sides of the relationship

**Comment by frodenas** [comment]
I see, but I don't yet understand why it is not picking up the hash if the value is nil (see https://github.com/cf-platform-eng/cf-containers-broker/pull/29#issuecomment-142187682)

**Comment by drnic** [comment]
I'm not sure how/why other protections are being bypassed - but https://github.com/cf-platform-eng/cf-containers-broker/blob/master/app/models/docker_manager.rb#L331 was complaining that `map` being invoked on `nil`

**Comment by frodenas** [comment]
`Parameters` at [brokerapi](https://github.com/pivotal-cf/brokerapi/blob/master/service_broker.go#L20 should have `omitempty` ), otherwise [cf-subway](https://github.com/cloudfoundry-community/cf-subway/blob/master/broker/api.go#L72) is going to send it as nil.

**Comment by drnic** [comment]
Tried explicitly setting Parameters to an empty struct but still seems to be nil.




Will look again tomorrow as well

**Comment by frodenas** [comment]
Messed up my own comment, was going to say `Parameters` should have `omitempty`. Never mind, I'll merge this PR, it's a safe check anyway.

**Comment by drnic** [comment]
Thanks; and I'll try omitempty too

**Comment by drnic** [comment]
PR for omitempty submitted upstream; and patched in cf-subway Godeps. Thanks.

**Pull request merged**
